# Generated by Django 5.2.17 on 2026-08-10 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='כותרת הכתבה.', max_length=200)),
                ('content', models.TextField(help_text='גוף הכתבה.')),
                ('tags', models.CharField(blank=True, help_text='תגיות מופרדות בפסיקים, לדוגמה: django,python,api', max_length=200)),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='תאריך הפרסום.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='מחבר הכתבה. נקבע אוטומטית לפי המשתמש המחובר.', on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'כתבה',
                'verbose_name_plural': 'כתבות',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='תוכן התגובה.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(help_text='הכתבה שאליה שייכת התגובה.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.article')),
                ('author', models.ForeignKey(help_text='כותב התגובה. נקבע אוטומטית לפי המשתמש המחובר.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'תגובה',
                'verbose_name_plural': 'תגובות',
                'ordering': ['created_at'],
            },
        ),
    ]
