# Generated by Django 5.2.17 on 2026-08-10 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='תיאור קצר על המשתמש, עד 300 תווים.', max_length=300),
        ),
    ]
